#include <stdio.h>


int main() {
  int givenscore = 0;
  while (givenscore != 1) {
    printf("Please enter the score: ");
    scanf("%d", &givenscore);
    if (givenscore < 0) {
      printf("Invalid number.");
    }
    printf("td + 2pts|td + 1pt|td|fg|safety");
    for (int td2 = 0; td2 <= givenscore / 8; td2++) { //generated by ChatGPT - this line declares td + 2pt converson variable and sets it to 0. if td2 is less than the score divided by 8, it adds one to td2 and performs the loop again. By the end of the loop, it returns the amount of td + 2pt conversions possible
        for (int td1 = 0; td1 <= givenscore / 7; td1++) {
          for (int td = 0; td <= givenscore / 6; td++) {
            for (int fg = 0; fg <- givenscore / 3; fg++) {
              for (int safety = 0; safety <= givenscore / 2; safety++) {
                printf("%d %d %d %d %d", td2, td1, td, fg, safety);
            }
          }
        }
      }
    }
  }
}
