#include <stdio.h>


int main() {
  int givenscore = 0; //declares givenscore as a variable 
  while (givenscore != 1) { // continues to prompt the user for a score until they enter 1 
    printf("Please enter the score: "); //prints the prompt 
    scanf("%d", &givenscore); //reads the user input 
    if (givenscore < 0) { //checks to make sure the score is valid 
      printf("Invalid number.");
      continue; //if invalid, goes back to the beginning of the while loop 
    }
    printf("\n");
    for (int td2 = 0; td2 <= givenscore / 8; td2++) { //generated by ChatGPT - this line declares td + 2pt converson variable and sets it to 0. if td2 is less than the score divided by 8, it adds one to td2 and performs the loop again. By the end of the loop, it returns the amount of td + 2pt conversions possible
        for (int td1 = 0; td1 <= givenscore / 7; td1++) {
          for (int td = 0; td <= givenscore / 6; td++) {
            for (int fg = 0; fg <= givenscore / 3; fg++) {
              for (int safety = 0; safety <= givenscore / 2; safety++) {
                int total = (td2 * 8) + (td1 * 7) + (td * 6) + (fg * 3) + (safety * 2); 
                if (total == givenscore) { //checks to make sure the total matches up with the score given 
                  printf("%d td + 2pt, %d td + 1pt, %d td, %d fg, %d safety \n", td2, td1, td, fg, safety);
              }
            }
          }
        }
      }
    }
  }
}
